# Generated by Django 6.0 on 2025-12-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavetype',
            old_name='is_active',
            new_name='allow_half_day',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='require_attachment',
            field=models.BooleanField(default=False),
        ),
    ]
