# Generated by Django 6.0 on 2025-12-11 06:44

import leave_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0003_leaverequest_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=leave_app.models.leave_attachment_upload_to),
        ),
    ]
